___DESCRIPTIVE STATISTICS:-
-Data set which is small in nature.
__ Measure of cental tendency-
-> Mean - it gives the average of the data. 
    - finding average of a data describes the whole story of the data set.
    - Mean average can be find only for the numerical data.
-> Mode - it used only for catagorical data.
    - The value that is frequently occur is the mode of the data.
-> Median - first we have to arrange the data in asscending order and the center value will be the median of the data.

__1.MEASURE OF CENTRAL TENDENCY:-
    -Mean
    -Mode
    -Median

In [1]:
import pandas as pd

In [13]:
df=pd.read_csv("C:/Users/Asus/Downloads/Sport car price.csv")

In [14]:
df

,Car Make,Car Model,Year,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD)
0,Porsche,911,2022,3,379,331,4,"101,200"
1,Lamborghini,Huracan,2021,5.2,630,443,2.8,"274,390"
2,Ferrari,488 GTB,2022,3.9,661,561,3,"333,750"
3,Audi,R8,2022,5.2,562,406,3.2,"142,700"
4,McLaren,720S,2021,4,710,568,2.7,"298,000"
...,...,...,...,...,...,...,...,...
1002,Koenigsegg,Jesko,2022,5,1280,1106,2.5,"3,000,000"
1003,Lotus,Evija,2021,Electric Motor,1972,1254,2,"2,000,000"
1004,McLaren,Senna,2021,4,789,590,2.7,"1,000,000"
1005,Pagani,Huayra,2021,6,764,738,3,"2,600,000"
1006,Rimac,Nevera,2021,Electric Motor,1888,1696,1.85,"2,400,000"

In [15]:
df=df.iloc[0:301,:]

In [16]:
df

,Car Make,Car Model,Year,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD)
0,Porsche,911,2022,3,379,331,4,"101,200"
1,Lamborghini,Huracan,2021,5.2,630,443,2.8,"274,390"
2,Ferrari,488 GTB,2022,3.9,661,561,3,"333,750"
3,Audi,R8,2022,5.2,562,406,3.2,"142,700"
4,McLaren,720S,2021,4,710,568,2.7,"298,000"
...,...,...,...,...,...,...,...,...
296,McLaren,Artura,2021,3,671,531,3,"225,000"
297,Mercedes-Benz,SLS AMG,2021,4,577,516,3.6,"247,500"
298,Nissan,370Z Nismo,2021,3.7,350,276,4.8,"45,790"
299,Porsche,Taycan,2022,Electric,616,774,2.6,"79,900"
300,Tesla,Model S,2022,Electric,1020,1050,1.98,"119,000"

In [17]:
df.dtypes

Car Make                   object
Car Model                  object
Year                        int64
Engine Size (L)            object
Horsepower                 object
Torque (lb-ft)             object
0-60 MPH Time (seconds)    object
Price (in USD)             object
dtype: object

In [18]:
df.describe()

              Year
count   301.000000
mean   2021.046512
std       3.421183
min    1965.000000
25%    2021.000000
50%    2021.000000
75%    2022.000000
max    2022.000000

In [19]:
df.describe(include="object")

,Car Make,Car Model,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD)
count,301,301,297,301,301,301,301
unique,36,108,26,86,70,36,187
top,Porsche,GT,4,503,590,3.5,"500,000"
freq,28,16,68,14,16,47,8

__2.MEASURE OF DISPERSION:-
    -range
    -quartiles
    -std
    -variance

In [23]:
df.describe()

              Year
count   301.000000
mean   2021.046512
std       3.421183
min    1965.000000
25%    2021.000000
50%    2021.000000
75%    2022.000000
max    2022.000000

In [21]:
range_1=df["Year"].max()-df["Year"].min()

In [22]:
range_1

57

These are the quartiles. 
25%	2021.000000
50%	2021.000000
75%	2022.000000
max	2022.000000
these will be use in outliears.

VARIANCE or std - distance of a data point from its mean.
 std 3.421183 is provided by the measure of dispersion beforehand. 
we dont need to calculate it.